'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Automatische My.Settings-Speicherfunktion"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property frmMain_ActiveUserControlIndex() As Integer
            Get
                Return CType(Me("frmMain_ActiveUserControlIndex"),Integer)
            End Get
            Set
                Me("frmMain_ActiveUserControlIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public Property frmMain_WindowState() As Integer
            Get
                Return CType(Me("frmMain_WindowState"),Integer)
            End Get
            Set
                Me("frmMain_WindowState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public Property frmMain_Top() As Integer
            Get
                Return CType(Me("frmMain_Top"),Integer)
            End Get
            Set
                Me("frmMain_Top") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public Property frmMain_Left() As Integer
            Get
                Return CType(Me("frmMain_Left"),Integer)
            End Get
            Set
                Me("frmMain_Left") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public Property frmMain_Width() As Integer
            Get
                Return CType(Me("frmMain_Width"),Integer)
            End Get
            Set
                Me("frmMain_Width") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public Property frmMain_Height() As Integer
            Get
                Return CType(Me("frmMain_Height"),Integer)
            End Get
            Set
                Me("frmMain_Height") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastExcelLoadPath() As String
            Get
                Return CType(Me("LastExcelLoadPath"),String)
            End Get
            Set
                Me("LastExcelLoadPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property btnAutoExecPressed() As Boolean
            Get
                Return CType(Me("btnAutoExecPressed"),Boolean)
            End Get
            Set
                Me("btnAutoExecPressed") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("character set=UNICODE_FSS;data source=vy-har-db2.hpc.local;initial catalog=D:\Pfw"& _ 
            "\Datenbank\Aktuell\PrinsDE.FB3;user id=SYSDBA;password=masterkey")>  _
        Public ReadOnly Property PRINSConnectionString() As String
            Get
                Return CType(Me("PRINSConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=vy-sql01.har.hpc.local\SQL;Initial Catalog=CRM_Prins;Integrated Secur"& _ 
            "ity=True")>  _
        Public ReadOnly Property CRM_PrinsConnectionString() As String
            Get
                Return CType(Me("CRM_PrinsConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("character set=UNICODE_FSS;data source=localhost;initial catalog=E:\Pfw\Database\P"& _ 
            "RINS3DE.FB3;user id=SYSDBA;password=masterkey")>  _
        Public ReadOnly Property ConnectionString() As String
            Get
                Return CType(Me("ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("character set=ISO8859_1;data source=vy-har-db2.hpc.local;initial catalog=d:\Pfw\D"& _ 
            "atenbank\Aktuell\Prins3Central.fdb;user id=SYSDBA;password=masterkey")>  _
        Public ReadOnly Property PrinsCentralConnection() As String
            Get
                Return CType(Me("PrinsCentralConnection"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=VY-SOE-SQL1\SQLEXPRESS;Initial Catalog=Refirm;Integrated Security=Tru"& _ 
            "e")>  _
        Public ReadOnly Property RefirmConnectionString() As String
            Get
                Return CType(Me("RefirmConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("character set=ISO8859_1;data source="" db2.har.hpc.local"";initial catalog=d:\Pfw\D"& _ 
            "atabase\Aktuell\PrinsES.fb;user id=SYSDBA;password=masterkey")>  _
        Public ReadOnly Property PrinsESConnection() As String
            Get
                Return CType(Me("PrinsESConnection"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("character set=ISO8859_1;data source=""db2.har.hpc.local"";initial catalog=d:\Pfw\Da"& _ 
            "tabase\Aktuell\PrinsIT.fb;user id=SYSDBA;password=masterkey")>  _
        Public ReadOnly Property PrinsITConnection() As String
            Get
                Return CType(Me("PrinsITConnection"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("character set=ISO8859_1;data source=""db2.har.hpc.local"";initial catalog=d:\Pfw\Da"& _ 
            "tabase\Aktuell\PrinsINT.fb;user id=SYSDBA;password=masterkey")>  _
        Public ReadOnly Property PrinsINTConnection() As String
            Get
                Return CType(Me("PrinsINTConnection"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("character set=ISO8859_1;data source=""db2.har.hpc.local"";initial catalog=d:\Pfw\Da"& _ 
            "tabase\Aktuell\PrinsFR.fb;user id=SYSDBA;password=masterkey")>  _
        Public ReadOnly Property PrinsFRConnection() As String
            Get
                Return CType(Me("PrinsFRConnection"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("character set=ISO8859_1;data source=VY-HAR-DB1.hpc.local;initial catalog=d:\Pfw\D"& _ 
            "atabase\Aktuell\PrinsAT.fb;user id=SYSDBA;password=masterkey")>  _
        Public ReadOnly Property PrinsATConnection() As String
            Get
                Return CType(Me("PrinsATConnection"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("character set=UNICODE_FSS;data source=vy-har-db2.hpc.local;initial catalog=d:\Pfw"& _ 
            "\Datenbank\Aktuell\PrinsDE.FB3;server type=0;user id=SYSDBA;password=masterkey")>  _
        Public ReadOnly Property ConnectionString1() As String
            Get
                Return CType(Me("ConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=vy-sql01.har.hpc.local\SAGE;Initial Catalog=HPCReweSKR04;Persist Secu"& _ 
            "rity Info=True;User ID=sa;Password=Pappnase2o13")>  _
        Public ReadOnly Property HPCReweSKR04ConnectionString() As String
            Get
                Return CType(Me("HPCReweSKR04ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("/Session/login?username=PRINS-CONNECTOR&domain=hpc.local&password=%C2%A7nt2rf!ce."& _ 
            "., ")>  _
        Public ReadOnly Property ARMAuthData() As String
            Get
                Return CType(Me("ARMAuthData"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://vy-har-8man-srv.eu.hpc.local")>  _
        Public ReadOnly Property ARMBaseAddress() As String
            Get
                Return CType(Me("ARMBaseAddress"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("character set=UNICODE_FSS;initial catalog=C:\Pfw\Database\PRINS3DE.FB3;data sourc"& _ 
            "e=PC-STR10A;user id=SYSDBA;password=masterkey")>  _
        Public ReadOnly Property ConnectionString2() As String
            Get
                Return CType(Me("ConnectionString2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("character set=UNICODE_FSS;data source=vy-har-db2.hpc.local;initial catalog=D:\Pfw"& _ 
            "\Datenbank\Aktuell\PrinsDE.FB3;user id=SYSDBA;password=masterkey")>  _
        Public ReadOnly Property PrinsReConnectionString() As String
            Get
                Return CType(Me("PrinsReConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("character set=UNICODE_FSS;data source=vy-har-db2.hpc.local;initial catalog=D:\Pfw"& _ 
            "\Datenbank\Aktuell\PrinsDE.FB3;user id=SYSDBA;password=masterkey")>  _
        Public ReadOnly Property PrinsDEConnection() As String
            Get
                Return CType(Me("PrinsDEConnection"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-executionPolicy bypass -file C:\Install\Scripts\HPC-Projects\HPCAG\HPCProject_fr"& _ 
            "omPrins.ps1 -Servername "":HOMESERVER"" -ProjectNumber "":PRJ_NUMMER"" -Projectname "& _ 
            """:PRJ_NAME1"" -Members "":Members"" -Year "":Year""")>  _
        Public Property ProjectScript() As String
            Get
                Return CType(Me("ProjectScript"),String)
            End Get
            Set
                Me("ProjectScript") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-executionPolicy bypass -file ""C:\Install\Scripts\HPC-Projects\HPCAG\HPCESTgroup_"& _ 
            "fromPrins.ps1"" -Groupname "":Groupname"" -Members "":Members""")>  _
        Public ReadOnly Property ESTGroupScript() As String
            Get
                Return CType(Me("ESTGroupScript"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PrjFolderAutoStart() As Boolean
            Get
                Return CType(Me("PrjFolderAutoStart"),Boolean)
            End Get
            Set
                Me("PrjFolderAutoStart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property fgMessagesCounter() As Integer
            Get
                Return CType(Me("fgMessagesCounter"),Integer)
            End Get
            Set
                Me("fgMessagesCounter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AzureBusServiceAutoStart() As String
            Get
                Return CType(Me("AzureBusServiceAutoStart"),String)
            End Get
            Set
                Me("AzureBusServiceAutoStart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AppMailbox() As String
            Get
                Return CType(Me("AppMailbox"),String)
            End Get
            Set
                Me("AppMailbox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AppMailFolder() As String
            Get
                Return CType(Me("AppMailFolder"),String)
            End Get
            Set
                Me("AppMailFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AppMailSession() As String
            Get
                Return CType(Me("AppMailSession"),String)
            End Get
            Set
                Me("AppMailSession") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ADUserExistsTemplateName() As String
            Get
                Return CType(Me("ADUserExistsTemplateName"),String)
            End Get
            Set
                Me("ADUserExistsTemplateName") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:hpcsqlserversdatalake.database.windows.net,1433;Initial Catalog=S"& _ 
            "QLDataLake;Persist Security Info=True;User ID=admhpcsql;Password=ZrB:4RyxLGlk")>  _
        Public ReadOnly Property SQLDataLakeConnectionString() As String
            Get
                Return CType(Me("SQLDataLakeConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("character set=UNICODE_FSS;data source=localhost;initial catalog=E:\Pfw\Database\P"& _ 
            "RINS3DE.FB3;user id=SYSDBA;password=masterkey")>  _
        Public ReadOnly Property ConnectionString3() As String
            Get
                Return CType(Me("ConnectionString3"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=vy-har-sql2.eu.hpc.local\ELO;Initial Catalog=Archiv1;Persist Security"& _ 
            " Info=True;User ID=elodb;Password=uE9t8zaJvr")>  _
        Public ReadOnly Property Archiv1ConnectionString() As String
            Get
                Return CType(Me("Archiv1ConnectionString"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CRM_Connect.My.MySettings
            Get
                Return Global.CRM_Connect.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
